<?php

return [
    //about us page
    'about-title' => 'About Us',
    'about-description' => 'This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain language errors, the Arabic text generator is useful for web designers in particular, where the customer often needs to see a real picture for site design. If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain language errors, the Arabic text generator is useful for web designers in particular, where the customer often needs to see a real picture for site design. If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain language errors, the Arabic text generator is useful for web designers in particular, where the customer often needs to see a real picture for site design. This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain language errors, the Arabic text generator is useful for web designers in particular, where the customer often needs to see a real picture for site design. If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain language errors, the Arabic text generator is useful for web designers in particular, where the customer often needs to see a real picture for site design.',
    'about-description-short' => 'This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain language errors, the Arabic text generator is useful for web designers in particular, where the customer often needs to see a real picture for site design. If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain language errors, the Arabic text generator is useful for web designers in particular, where the customer often needs to see a real picture for site design.',

    //products page
    'products-title' => 'Our Products',
    'products-description' => 'This text is an example that can be replaced in the same space, where you can create this text from the Arabic text generator, where you can generate text or other texts in addition to increasing the number of characters generated by the application. This text is an example that can be replaced in the same space, where you can create this text from the Arabic text generator, where you can generate text or other texts in addition to increasing the number of characters generated by the application.',
    'product-title' => 'Swedish wood treated first class set',
    'product-description' => 'Swedish wood set treated first class, painted with specialized sealer paint for wood, and on top of it a layer of lacquer material that is resistant to water and sun strokes

    The seating capacity is 7 people or more, and it consists of:
    A two-meter chair for 3 people A one-and-a-half meter chair for two people A two-meter chair with one person One-meter chair with one person table meter * 70 cm
    The customer can choose the shape and color of the wood and choose the color of the mattress',

    //slider
    'slider-title' => 'Welcome To The Largest Marketplace',
    'slider-description' => 'Buy and sell everything from used cars to mobile phones and computers, or search for property, jobs and more',

    //partner section
    'partner-name' => 'partner name',
    'partner-job-title' => 'job title',
    'partner-description' => 'your own. It features different random texts in Latin and Cyrillic to generate examples of texts in different languages. LoremIpsum360° also gives you the ability to add punctuation, accents and special characters to be closer to languages',
];